version: '3.8'

services:
  auth:
    build:
      context: .
      dockerfile: auth/Dockerfile
    container_name: auth_service
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET_KEY=RAHASIA
      - JWT_EXPIRATION_TIME=1h

  users:
    build:
      context: .
      dockerfile: users/Dockerfile
    container_name: users_service
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGO_URI=mongodb+srv://johanesraphaeln:0hIfMj4iybCTokgC@db-joel-betest.u0k8p.mongodb.net/?retryWrites=true&w=majority&appName=db-joel-betest
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis_service
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  redis_data:
